### ISSUE TITLE
Can't make it work with google or facebook

### ISSUE THREAD

**Issue by tfagart** [jimdigriz/freeradius-oauth2-perl#1]
Hello,

First thank's a lot for this freeradius module which will be very interesting for futur use.

Unfortunately I've got no chance to make it work with google or facebook. I've understand that if oauth provider does not provide  Resource Owner Password Credentials Grant, this is not going to work.

I've read your ISSUE/TODO but I haven't understand well how to do with goole.

This is the freeradius/module log i've got : 

++update control {
++} # update control = noop
rlm_perl: Added pair NAS-Port = 0
rlm_perl: Added pair Realm = gmail.com
rlm_perl: Added pair User-Name = user@gmail.com
rlm_perl: Added pair Stripped-User-Name = user
rlm_perl: Added pair NAS-IP-Address = 192.168.2.11
rlm_perl: Added pair Message-Authenticator = 0x41f8236edf2403f213990dca445ff2a7
rlm_perl: Added pair User-Password = password
rlm_perl: Added pair Auth-Type = oauth2-perl
++[oauth2-perl] = ok
[oauth_files] users: Matched entry DEFAULT at line 210
++[oauth_files] = ok
+} # group authorize = ok
Found Auth-Type = oauth2-perl
# Executing group from file /usr/local/etc/raddb/sites-enabled/portal

+group oauth2-perl {
rlm_perl: GET https://accounts.google.com/.well-known/openid-configuration
rlm_perl: Accept-Encoding: gzip, x-gzip, deflate, x-bzip2
rlm_perl: From: user@gmail.com
rlm_perl: User-Agent: freeradius-oauth2-perl/0.1 (+https://github.com/jimdigriz/freeradius-oauth2-perl; libwww-perl/6.13)
rlm_perl: X-Cache-Key: gmail.com
rlm_perl:
rlm_perl: (no content)
rlm_perl: HTTP/1.1 200 OK
rlm_perl: Cache-Control: public, max-age=604800
rlm_perl: Connection: close
rlm_perl: Date: Thu, 19 Mar 2015 18:46:06 GMT
rlm_perl: Server: GSE
rlm_perl: Content-Length: 712
rlm_perl: Content-Type: application/json
rlm_perl: Expires: Thu, 26 Mar 2015 18:46:06 GMT
rlm_perl: Last-Modified: Fri, 05 Dec 2014 04:03:03 GMT
rlm_perl: Alternate-Protocol: 443:quic,p=0.5
rlm_perl: Client-Date: Thu, 19 Mar 2015 18:46:06 GMT
rlm_perl: Client-Peer: 2a00:1450:4007:80d::200d:443
rlm_perl: Client-Response-Num: 1
rlm_perl: Client-SSL-Cert-Issuer: /C=US/O=Google Inc/CN=Google Internet Authority G2
rlm_perl: Client-SSL-Cert-Subject: /C=US/ST=California/L=Mountain View/O=Google Inc/CN=accounts.google.com
rlm_perl: Client-SSL-Cipher: ECDHE-RSA-AES128-SHA
rlm_perl: Client-SSL-Socket-Class: IO::Socket::SSL
rlm_perl: X-Cache-Expires: 1426792721
rlm_perl: X-Content-Type-Options: nosniff
rlm_perl: X-XSS-Protection: 1; mode=block
rlm_perl:
rlm_perl: {
rlm_perl:  "issuer": "accounts.google.com",
rlm_perl:  "authorization_endpoint": "https://accounts.google.com/o/oauth2/auth",
rlm_perl:  "token_endpoint": "https://www.googleapis.com/oauth2/v3/token",
rlm_perl:  "userinfo_endpoint": "https://www.googleapis.com/plus/v1/people/me/openIdConnect",
rlm_perl:  "revocation_endpoint": "https://accounts.google.com/o/oauth2/revoke",
rlm_perl:  "jwks_uri": "https://www.googleapis.com/oauth2/v2/certs",
rlm_perl:  "response_types_supported": [
rlm_perl:   "code",
rlm_perl:   "token",
rlm_perl:   "id_token",
rlm_perl:   "code token",
rlm_perl:   "code id_token",
rlm_perl:   "token id_token",
rlm_perl:   "c...
rlm_perl: (+ 200 more bytes not shown)
rlm_perl: POST https://www.googleapis.com/oauth2/v3/token
rlm_perl: Accept-Encoding: gzip, x-gzip, deflate, x-bzip2
rlm_perl: From: user@gmail.com
rlm_perl: User-Agent: freeradius-oauth2-perl/0.1 (+https://github.com/jimdigriz/freeradius-oauth2-perl; libwww-perl/6.13)
rlm_perl: Content-Length: 193
rlm_perl: Content-Type: application/x-www-form-urlencoded
rlm_perl:
rlm_perl: scope=openid&username=user%40gmail.com&password=password&grant_type=password&client_id=115158283190-ha33milannvb28vphm7j7uu9leeaptoq.apps.googleusercontent.com&client_secret=notasecret
rlm_perl: HTTP/1.1 400 Bad Request
rlm_perl: Cache-Control: private, max-age=0
rlm_perl: Connection: close
rlm_perl: Date: Thu, 19 Mar 2015 18:46:06 GMT
rlm_perl: Server: GSE
rlm_perl: Vary: Origin
rlm_perl: Vary: X-Origin
rlm_perl: Content-Encoding: gzip
rlm_perl: Content-Type: application/json; charset=UTF-8
rlm_perl: Expires: Thu, 19 Mar 2015 18:46:06 GMT
rlm_perl: Alternate-Protocol: 443:quic,p=0.5
rlm_perl: Client-Date: Thu, 19 Mar 2015 18:46:06 GMT
rlm_perl: Client-Peer: 2a00:1450:4007:80e::200a:443
rlm_perl: Client-Response-Num: 1
rlm_perl: Client-SSL-Cert-Issuer: /C=US/O=Google Inc/CN=Google Internet Authority G2
rlm_perl: Client-SSL-Cert-Subject: /C=US/ST=California/L=Mountain View/O=Google Inc/CN=_.storage.googleapis.com
rlm_perl: Client-SSL-Cipher: ECDHE-RSA-AES128-SHA
rlm_perl: Client-SSL-Socket-Class: IO::Socket::SSL
rlm_perl: Client-Transfer-Encoding: chunked
rlm_perl: X-Content-Type-Options: nosniff
rlm_perl: X-Frame-Options: SAMEORIGIN
rlm_perl: X-XSS-Protection: 1; mode=block
rlm_perl:
rlm_perl: \37\x8B\10\0\0\0\0\0\0\0\xAB\xE6RPJ-_\xCA/R\xB2RP\xCA\xCC+K\xCC\xC9L\x89/J-,M-.Q\xD2\x81I\xC6\xA7\xA4\26'\27e\26\x94d\xE6\xE7\x81\24zB\24*\xF8;\x96\x96d(\30)\xA4\27%\xE6\x95(\x94T\26\xA4Z)\x048\6\7\x87\xFB\7\xB9(q\xD5r\1\0-o<\1^\0\0\0
rlm_perl: Added pair NAS-Port = 0
rlm_perl: Added pair Realm = gmail.com
rlm_perl: Added pair User-Name = user@gmail.com
rlm_perl: Added pair NAS-IP-Address = 192.168.2.11
rlm_perl: Added pair Stripped-User-Name = user
rlm_perl: Added pair Stripped-User-Name = user@
rlm_perl: Added pair User-Password = password
rlm_perl: Added pair Message-Authenticator = 0x41f8236edf2403f213990dca445ff2a7
rlm_perl: Added pair Reply-Message = Error: invalid_request
rlm_perl: Added pair Reply-Message = Invalid OAuth 2 grant type: PASSWORD
rlm_perl: Added pair Auth-Type = oauth2-perl
++[oauth2-perl] = reject
+} # group oauth2-perl = reject
Failed to authenticate the user.
Login incorrect: [user@gmail.com/password](from client localhost port 0)
} # server portal
Using Post-Auth-Type REJECT
# Executing group from file /usr/local/etc/raddb/sites-enabled/portal

+group REJECT {
[attr_filter.access_reject]     expand: %{User-Name} -> user@gmail.com
attr_filter: Matched entry DEFAULT at line 11
++[attr_filter.access_reject] = updated
+} # group REJECT = updated
Delaying reject of request 0 for 1 seconds
Going to the next request
Waking up in 0.3 seconds.
Sending delayed reject for request 0
Sending Access-Reject of id 200 to 127.0.0.1 port 42856
        Reply-Message += "Error: invalid_request"
        Reply-Message += "Invalid OAuth 2 grant type: PASSWORD"
Waking up in 4.9 seconds.
Cleaning up request 0 ID 200 with timestamp +3

Could you help ?

Thanks

Regards 

Thomas

**Comment by jimdigriz** [comment]
As you already figured out, Google/Facebook are not supported.  I'll try to find some time at the weekend to see if there is a authorisation/authentication flow that could work here.

Are you trying to use 802.1X (or some EAP method) here, or are you just looking to do straight forward authentication of your users against Google/Facebook (for example for a web portal)?

**Comment by tfagart** [comment]
Thanks for you answer and your effort to make it work with 
google/facebook, I have used PAP between a NAS (actually a captive 
portal) and the Radius Server.


Le 2015-04-08 23:44, Alexander Clouter a écrit :

**Comment by jimdigriz** [comment]
One possibility seems to be that both [Facebook](https://developers.facebook.com/docs/facebook-login/using-login-with-devices) and [Google](https://developers.google.com/identity/protocols/OAuth2ForDevices) support ['device_code' flow](https://tools.ietf.org/html/draft-ietf-oauth-v2-06#section-2.7); something that never made it into the final [OAuth2 RFC](https://tools.ietf.org/html/rfc6749#section-4.3).

This means that either:
 * you need to permit unauthenticated users access to Facebook's and Google's OAuth2 endpoints, this may be tricky as it is all SSLed and could be hard to stop them using Facebook/Google generally
 * the user uses their phone with a 3G/4G data plan to do the authentication; but of course if they have no data plan or mobile reception you just get an annoyed user

This will involve a good chunk of development time, to get the user experience to be slick, can you do the HTML/Javascript/firewalling side of things?  Is the captive portal your own solution or something you sourced from elsewhere (either bought or downloaded)?

I'll keep thinking on what this would look like, but it will need development work from your end on the captive portal infrastructure?  Is this something you can do?

**Comment by jimdigriz** [comment]
If you can use unbound as your DNS resolver for your captive portal, then its python scriptable interface could be used to dynamically permit Google/Facebook OAuth2 endpoints IPs (using [iptables `ipset`](http://ipset.netfilter.org/ipset.man.html#lbAQ)); letting you whitelist DNS entries rather than having to rely on a crude and unreliable IP based whitelist.

This means we could use the traditional [Authorization Code Grant](https://tools.ietf.org/html/rfc6749#section-4.1) flow which is supported everywhere, and something all users would be familiar with.

Are you comfortable with Python, iptables and can write some HTML/Javascript?  I could do this all myself, however I plan to put my personal time into other projects.  If there is someone (you?) who can do the captive portal end of the work and provide documentation so others can do this for themselves, I am happy to put time into this to get this all working.

**Comment by tfagart** [comment]
Hello Alexander,

Well the idea was to use your module instead of using the using Web 
Authentication. This will enable us to authenticate captive portal users 
either with traditional mysql freeradius backend or with your module 
when this is facebook or google users (using proxy.conf)

This would have been easier than letting special flow go through the 
captive portal.

But you tell that Google/Facebook does not follow oauth2 standard, then 
your module won't work, right ?

Regards

Thomas

**Comment by jimdigriz** [comment]
Google and Facebook *do* follow the OAuth2 standard.  To resolve this problem I need someone help me and split the work that needs to be done.  As well as changes to freeradius-oauth2-perl, someone needs to make changes your captive portal to use the [DNS server unbound](https://www.unbound.net/documentation/pythonmod/), write some python, and write some HTML/Javascript to give the user a nice slick process.

Although I could do all this work myself, I would rather put the time into other projects I am interested in.  To motivate me, having the work needed halved, would help a lot.

**Comment by tfagart** [comment]
Ok then I haven't understand properly. Again I'll try to explain a 
little bit better.

First I'm willing to code, because that's what we've already done on 
Pfsense captive portal based on BSD.

Today the solution that works does the following :

1. Captive portal intercept any HTTP request and redirect it to a login 
web page served by the captive portal
2. Users enters their credential (login/pass) and send the HTTP request 
to the captive portal web server
3. Captive portal send the Radius request to Freeradius Server using PAP
4. Freeradius checks in the backend (mysql) and send a response to the 
captive portal
5.  If response is Access Accept the captive  portal allow End User to 
surf (firewalling) and so on.

By using your module I though this was going to be like that :

1. Captive portal intercept any HTTP request and redirect it to a login 
web page served by the captive portal
2. Users enters their credential (login/pass) and send the HTTP request 
to the captive portal web server
3. Captive portal send the Radius request to Freeradius Server using PAP
4. Freeradius checks in the backend (freeradius-oauth2-perl)
5. Oauth2 freeradius module send auth request to Google/Facebook API(HTTPS)
6. Google/Facebook API answer yes to Freeradius
7. Freeradius send an Access Accept to Captive Portal
8. If response is Access Accept the captive  portal allow End User to 
surf (firewalling) and so on.

I guess I'm going to spend more time on the oauth2 RFC to understand 
better what you propose, and then  to help

**Comment by timmrogers** [comment]
I'm wondering if there has been any progress towards making this module work with Google Apps for Education. 

I would love to be able to use it with our Untangle firewall and captive portal. 

If there is something that I might be able to do to help, I'm willing. It sounds like it might be possible, but that it could be a bigger job than you'd like to do on your own, and that it isn't functionality that you need.

What needs to be done to make it work? Is there something that I could to to help?

Thank you!

**Comment by jimdigriz** [comment]
You pretty much hit the nail on the head, at work we are only condemned to use Office365 (...though better than having your own MS stack I will admit) so can cheat and use the Resource Owner Password Credentials Grant flow, so my immediate motivation here ended.

I am keen to see this project go further though as the problem is interesting.  What have you got available at your end resource wise?  Really this is to find out if I will be committing myself to 90%+ of the work, or 50%.

Things that would be helpful are people who are:

 * able to make any necessary/experimental changes to your captive portal
 * comfortable with FreeRADIUS and able to diagnose problems
 * network savy people, tcpdump, iptables/shell scripting, ...as I suspect we will need to dynamically whitelist Google's websites for the OAuth2 step

Have you got those kind of things at your end?  I used to work in academentia as a network monkey in the UK, so have a pile of old eduroam colleagues I will reach out to find out if there is interest in working on this.

Anyway, I'll find the time this week to re-evaluate how GApps support could be added, if at all.  I think a vaguely recall having a plan where the captive portal was straight forward (with some DNS+dynamic firewalling trickery) and if you could handle a pre-registration step (mobile, out-of-bound email, but you would need email/SMS reception), a full 802.1X authentication via OAuth2 could be possible.

**Comment by timmrogers** [comment]
Thanks, Alexander.

It is just me here, and while I have been using Linux in various ways for
many years now, and have some experience with FreeRADIUS, iptables, tcpdump
and so on - I am not expert in any of them. And Oauth2 is completely new to
me - and reading Google's documentation made me want to throw up my hands
in despair! :)

The real barrier for me, though, is that I don't have any good way to test
changes to the firewall. Even if I was comfortable with the code - which I
likely could make peace with, at least for the things that we might need to
change - I wouldn't want to play with it during school hours. That would
only leave whatever evenings that I could find time to come to campus and
work on the project. I'm willing to do that from time to time, but it would
be difficult to find time to do so too often.

Perhaps you could explore the issue a little more, and see if you can see a
way to do this.

For me, "pre-registration" would likely be a show-stopper. I really need
something which would "just work". If my users would need to jump through
too many hoops, it would be better for us to just authenticate against a
local database, even if it didn't share passwords with Google Apps.

But if we can come up with an elegant system, I think that I have the time
and skills to be of some help to you. Perhaps 30%/70%? :)

Thanks again.

**Comment by jimdigriz** [comment]
Unless someone can figure out how to contribute a non-webportal option or to make things better here, I'm going to state that for now it is out of scope handling providers that do not support [ Resource Owner Password Credentials Grant (eg. Google, Facebook, ...)](https://tools.ietf.org/html/rfc6749#section-4.3).

**Comment by ernani** [comment]
ROPC is strongly discouraged as of today, as per 2.0 spec and omitted in 2.1 as per this link:
https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-19#section-2.4

Is there any possibility to create an update so that we can use the authorization code flow or implicit flow with PKCE?

Do you require to know the username and pwd of the user for FreeRadius? If so, why?

Best Regards!

**Comment by jimdigriz** [comment]
ROPC has [*always* been discouraged: "The authorization server should take special care when enabling this grant type and only allow it when other flows are not viable."](https://www.rfc-editor.org/rfc/rfc6749#section-4.3)

The problem is not FreeRADIUS or any given RADIUS server or client supplicant, the problem is in how 802.1X fundamentally works, as described in the second paragraph of the README.md:

> The [Password Grant](https://oauth.net/2/grant-types/password/) is necessary as it is the only grant flows that does not require user interaction with a web browser (think "log in via Google/Facebook/LinkedIn/...") which is impossible during an 802.1X authentication as the user's workstation does not have an IP address.

802.1X uses EAPOL which is a Layer-2 protocol and this all occurs before an IP address is assigned.

There is no way for a user to authenticate via a web browser when their workstation has no IP.

The only possible way around this is to use the [OOB Device orientated flow](https://www.rfc-editor.org/rfc/rfc8628), but this then puts a hard requirement on the user having OOB access to the Internet to perform the authentication. The problem here though is 802.1X is not really set up to handle the long authentication polls without some serious hackery and poking of the switch/wifi infrastructure involved; everything expects the authentication to take typically less than 10 seconds.

**Comment by ernani** [comment]
Thanks for the prompt reply! I was able to see it in the docs but thought of rather confirming as I was unaware how the 802.1X works. After your explanations I got to understand more about the whole thing.

I've found along with a friend here about the OpenWisp tool. It seems to create a OIDC authorization code flow with social logins, and then creating users and somehow a password for it and store in freeradius db.
https://openwisp-radius.readthedocs.io/en/stable/

Then, the Captive portal such as opnsense or pfsense can use that db (freeradius) to proceed with the authentication itself. I have to test it but I don't have an env here, will try later to repro something with OpenWRT. Thanks!

**Comment by jimdigriz** [comment]
When you talk about 'captive page' this is something quite different. You are placing them into a 'holding' VLAN until they use a web browser to gain access. This is *not* 802.1X.

You may be able to use a captive portal as an enrollment process backed by OIDC to authorize the creation of *another* set of user credentials that are stored locally but this is literally just automating a process that could otherwise be someone emailing the hotspot provider and asking for credentials. Crucially this is not authenticating by OIDC, this is creating static credentials by way of OIDC so you can use TTLS/PAP for future sessions.

The problem is to light up a captive portal (holding/enrollment VLAN) is in describing the process to others and linking the several software components together in a way that the administrator is not going to break.

Of important note, playing with VLANs, DHCP servers, DNS servers, FreeRADIUS and Perl/Python/whatever is easily 10x more difficult than easier tasks like reading the existing documentation and glancing at the relevant RFCs to understand why it is difficult, but I still get GitHub issues from people grumbling that they cannot... ;)

Maybe one day I will get around to blowing the dust off my prototype that leans on the device code flow...that will be a commercial endeavor though.

**Comment by ernani** [comment]
Thanks for your reply here! Fully aware of complexities on fiddling with all these components. The issue here is not that I am doing that, but, the captive portal itself, so that's how vendors implement it for WIFI auth.

Certainly a device code flow here would behave way better, with both an access token and refresh_token and I am fully aware how to implement this in the IDP, but, since given the situation where the WIFI auth can't allow user to browse all websites but some certain whitelisted IPs, that validation of the device code would be required to exist in those whitelisted ips so that it would allow the flow to happen before clearing the way for other websites.

The only difference would be that the freeradius module would be polling the IDP endpoint for a token while the user validates the device code...and then the user would be created in freeradius, after consuming the access token as you currently do now with ROPC but certainly way more elegant and disengaging the ROPC from the IDP.

**Comment by jimdigriz** [comment]
> The issue here is not that I am doing that, but, the captive portal itself, so that's how vendors implement it for WIFI auth.

The captive portal is a distraction. Using a captive portal removes the use of 802.1X. For captive portals the users workstation has an IP address. For 802.1X, no IP, you need your solution to work within that environment.

If all you are doing is bootstrapping the creation of some other credentials, you may as well just push EAP-TLS profiles to the client; this is already standardised and far safer.

> Certainly a device code flow here would behave way better, with both an access token and refresh_token and I am fully aware how to implement this in the IDP, but, since given the situation where the WIFI auth can't allow user to browse all websites but some certain whitelisted IPs, that validation of the device code would be required to exist in those whitelisted ips so that it would allow the flow to happen before clearing the way for other websites.

You cannot whitelist IPs, you have to whitelist domains. It means you now need something to transparently process HTTPS and filter based on the SNI. This is all very possible, and software is very mutable, but this is out of scope of this project, mostly as I am not interested in being the site administrator or teaching people how to do this...for free.

> The only difference would be that the freeradius module would be polling the IDP endpoint for a token while the user validates the device code...and then the user would be created in freeradius, after consuming the access token as you currently do now with ROPC but certainly way more elegant and disengaging the ROPC from the IDP.

No, it is worse. You need to stop thinking this as a software problem, it is not. It is a usability problem.

You are seeing the problem as something that exists at the authentication server, but the software there is *trivial* to implement and not important. The problem is in how the *supplicant* and *authenticator* work, more importantly are both tuned to the whole authentication process taking less than ten seconds. I mentioned earlier, "everything expects the authentication to take typically less than 10 seconds" and I think you missed the impact of this statement.

![image](https://github.com/jimdigriz/freeradius-oauth2-perl/assets/2567406/6a939864-3119-4fa1-9560-6198c8165313)

We are not able to change those components and this is the problem OIDC/OAuth2 over 802.1X has. Sure we can tweak `hostapd` and one day that will appear in Android/ChromeOS, but what about macOS and Windows and I also suspect neither of us can amend the software running on a Cisco switch or Aerohive/Mikrotik AP...right? :)

You are thinking about this purely as a developer and not from the perspective of the poor helpdesk fielding lots of calls about failed authentications and timeouts. There is a reason people use Captive Portals, and that is because of the UX and support burden, not because they are lazy.

Of course, if you think I am wrong, patches welcomed!
