### ISSUE TITLE
NTRadPing Test Utility

### ISSUE THREAD

**Issue by senseyk-git** [jimdigriz/freeradius-oauth2-perl#39]
Hi, 
first thanks for your help on my next issue ^^.

i succeed to perform a simple radtest with:
`radtest user@MyDomain.com MyPassword 127.0.0.1 0 testing123
`
it return:
`Sent Access-Request Id 127 from 0.0.0.0:46304 to 127.0.0.1:1812 length 96
        User-Name = "user@MyDomain.com"
        User-Password = "MyPassword"
        NAS-IP-Address = AnIpAddress
        NAS-Port = 0
        Message-Authenticator = 0x00
        Cleartext-Password = "MyPassword"
Received Access-Accept Id 127 from 127.0.0.1:1812 to 127.0.0.1:46304 length 34
        Class = 0x4649444f325f416363657373
`

i then would like to try with "NTRadPing Test Utility" to see if it works 
it look like this:
![Capture](https://github.com/jimdigriz/freeradius-oauth2-perl/assets/115167413/b2953b72-a98f-459c-8ce9-996eee7c00fc)

i added a client that you will be able to find with the name "clientName" using the Freeradius public ip address.
and when trying send my request i get this error:
`ERROR: No Auth-Type found: rejecting the user via Post-Auth-Type = Reject`

Can you help figured it out what i do wrong please ?

what i got with debug mode, i do a radtest and then i try to send the request with NTRadPing Test Utility:
[DebugModeResults.txt](https://github.com/jimdigriz/freeradius-oauth2-perl/files/11807542/DebugModeResults.txt)

**Comment by jimdigriz** [comment]
From the debug, it looks like you have done nothing wrong (good work on following the instructions!) so I am suspecting the process of sanitising the logs may have hidden the underlying problem.

I think the username (case-sensitive) may have had a typo, this is just a guess.

The only reason the module returns 'notfound' (line 1100 in the debug you sent) is is the user is unknown to it, which is why I suspect `user@MyDomain.com` may have changed between your `radtest` test and your NTRadPing test.
