### ISSUE TITLE
Device ID or Operating system

### ISSUE THREAD

**Issue by yuhongwei380** [jimdigriz/freeradius-oauth2-perl#45]
I noticed that the corresponding login record can be found in Azure, so how to change the code so that Azure can receive the login device ID or operating system? Looking forward to your reply, thanks

**Comment by jimdigriz** [comment]
Though 'device ID' (`Calling-Station-Id` which is the MAC address, likely randomised!) is communicated to the RADIUS server, you cannot do what you want for a few major reasons:
 * nothing in the [authentication request to Entra](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth-ropc#authorization-request) lets you communicate such metadata to Entra
 * the connecting client does not communicate any information about the host (eg. the OS) in the request (nothing about EAP or EAP-TTLS supports this)

So the problem is that information is not made available to the RADIUS server...and where it is, there is no way to communicate this to Entra in the request that we use.

Does this make sense to you?

**Comment by yuhongwei380** [comment]
So according to my plan, the user and data are verified through the graph api, but the data cannot be transferred to azure, right?

**Comment by jimdigriz** [comment]
> So according to my understanding, the graph API is used to verify users and data, but the data cannot be transferred to Azure, right?

Correct...but also some of that data (ie. OS) is not available to the RADIUS server.

**Comment by yuhongwei380** [comment]
> > So according to my understanding, the graph API is used to verify users and data, but the data cannot be transferred to Azure, right?
> 
> Correct...but also some of that data (ie. OS) is not available to the RADIUS server.

Thanks for reply~
